spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialsize: 5
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    # 每隔多长时间进行空闲连接回收
    timeBetweenEvictionRunMillis: 60000
    # 每个连接的最小存活时间
    minEvictableIdleTimeMillis: 300000
    # 检验连接是否正常
    validationQuery: SELECT 1 FROM DUAL
    # 空闲时对连接进行检查
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置拦截统计的filters, 去掉后监控界面的sql无法统计
    filters: stat,wall,log4j
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

mytest:
  jwt:
    # 过期时间
    expire: 604800
    # 请求头的key
    header: Authorization
    # 密匙
    secret: f4e2e52034348f86b67cde581c0f9eb5

